In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
from tensorflow import keras

In [ ]:
df_train = pd.read_csv('DiseaseTraining.csv')
df_test = pd.read_csv('DiseaseTesting.csv')

In [ ]:
df_train.head()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          1                     1                    0          0   
2        1          0                     1                    0          0   
3        1          1                     0                    0          0   
4        1          1                     1                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  scurring  \
0       0           0             0        0                 0  ...         0   
1       0           0             0        0                 0  ...         0   
2       0           0             0        0                 0  ...         0   
3       0           0             0        0                 0  ...         0   
4       0           0             0        0                 0  ...         0   

   skin_peeling  silver_like_dusting  small_dents_in_nails  \
0             0                    0                     0   
1             0                    0                     0   
2             0                    0                     0   
3             0                    0                     0   
4             0                    0                     0   

   inflammatory_nails  blister  red_sore_around_nose  yellow_crust_ooze  \
0                   0        0                     0                  0   
1                   0        0                     0                  0   
2                   0        0                     0                  0   
3                   0        0                     0                  0   
4                   0        0                     0                  0   

          prognosis  Unnamed: 133  
0  Fungal infection           NaN  
1  Fungal infection           NaN  
2  Fungal infection           NaN  
3  Fungal infection           NaN  
4  Fungal infection           NaN  

[5 rows x 134 columns]

In [ ]:
df_train.drop(columns='Unnamed: 133', inplace=True)
df_train.head(3)

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          1                     1                    0          0   
2        1          0                     1                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       0           0             0        0                 0  ...   
2       0           0             0        0                 0  ...   

   blackheads  scurring  skin_peeling  silver_like_dusting  \
0           0         0             0                    0   
1           0         0             0                    0   
2           0         0             0                    0   

   small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                     0                   0        0                     0   
1                     0                   0        0                     0   
2                     0                   0        0                     0   

   yellow_crust_ooze         prognosis  
0                  0  Fungal infection  
1                  0  Fungal infection  
2                  0  Fungal infection  

[3 rows x 133 columns]

In [ ]:
df_test.head(20)

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0         1          1                     1                    0          0   
1         0          0                     0                    1          1   
2         0          0                     0                    0          0   
3         1          0                     0                    0          0   
4         1          1                     0                    0          0   
5         0          0                     0                    0          0   
6         0          0                     0                    0          0   
7         0          0                     0                    0          0   
8         0          0                     0                    0          0   
9         0          0                     0                    0          0   
10        0          0                     0                    0          0   
11        0          0                     0                    0          0   
12        0          0                     0                    0          0   
13        0          0                     0                    0          0   
14        1          0                     0                    0          0   
15        0          0                     0                    0          0   
16        1          1                     0                    0          0   
17        0          1                     0                    0          0   
18        0          0                     0                    0          0   
19        0          0                     0                    0          0   

    chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0        0           0             0        0                 0  ...   
1        1           0             0        0                 0  ...   
2        0           0             1        1                 1  ...   
3        0           0             0        0                 0  ...   
4        0           0             1        0                 0  ...   
5        0           0             0        0                 0  ...   
6        0           0             0        0                 0  ...   
7        0           0             0        0                 0  ...   
8        0           0             0        0                 0  ...   
9        0           0             0        0                 0  ...   
10       0           0             0        0                 0  ...   
11       0           0             0        1                 0  ...   
12       0           0             0        0                 0  ...   
13       0           0             0        0                 0  ...   
14       0           0             0        0                 0  ...   
15       1           0             0        0                 0  ...   
16       0           0             0        0                 0  ...   
17       1           1             0        0                 0  ...   
18       1           0             0        0                 0  ...   
19       0           1             0        0                 0  ...   

    blackheads  scurring  skin_peeling  silver_like_dusting  \
0            0         0             0                    0   
1            0         0             0                    0   
2            0         0             0                    0   
3            0         0             0                    0   
4            0         0             0                    0   
5            0         0             0                    0   
6            0         0             0                    0   
7            0         0             0                    0   
8            0         0             0                    0   
9            0         0             0                    0   
10           0         0             0                    0   
11           0         0             0                

In [ ]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4920 entries, 0 to 4919
Columns: 133 entries, itching to prognosis
dtypes: int64(132), object(1)
memory usage: 5.0+ MB


In [ ]:
df_train.isnull().sum()

itching                 0
skin_rash               0
nodal_skin_eruptions    0
continuous_sneezing     0
shivering               0
                       ..
inflammatory_nails      0
blister                 0
red_sore_around_nose    0
yellow_crust_ooze       0
prognosis               0
Length: 133, dtype: int64

In [ ]:
df_train['prognosis'].value_counts()

prognosis
Fungal infection                           120
Allergy                                    120
GERD                                       120
Chronic cholestasis                        120
Drug Reaction                              120
Peptic ulcer diseae                        120
AIDS                                       120
Diabetes                                   120
Gastroenteritis                            120
Bronchial Asthma                           120
Hypertension                               120
Migraine                                   120
Cervical spondylosis                       120
Paralysis (brain hemorrhage)               120
Jaundice                                   120
Malaria                                    120
Chicken pox                                120
Dengue                                     120
Typhoid                                    120
hepatitis A                                120
Hepatitis B                                120
Hepatitis C                                120
Hepatitis D                                120
Hepatitis E                                120
Alcoholic hepatitis                        120
Tuberculosis                               120
Common Cold                                120
Pneumonia                                  120
Dimorphic hemmorhoids(piles)               120
Heart attack                               120
Varicose veins                             120
Hypothyroidism                             120
Hyperthyroidism                            120
Hypoglycemia                               120
Osteoarthristis                            120
Arthritis                                  120
(vertigo) Paroymsal  Positional Vertigo    120
Acne                                       120
Urinary tract infection                    120
Psoriasis                                  120
Impetigo                                   120
Name: count, dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le = LabelEncoder()
df_train['prognosis'] = le.fit_transform(df_train['prognosis'])
df_train.head()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          1                     1                    0          0   
2        1          0                     1                    0          0   
3        1          1                     0                    0          0   
4        1          1                     1                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       0           0             0        0                 0  ...   
2       0           0             0        0                 0  ...   
3       0           0             0        0                 0  ...   
4       0           0             0        0                 0  ...   

   blackheads  scurring  skin_peeling  silver_like_dusting  \
0           0         0             0                    0   
1           0         0             0                    0   
2           0         0             0                    0   
3           0         0             0                    0   
4           0         0             0                    0   

   small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                     0                   0        0                     0   
1                     0                   0        0                     0   
2                     0                   0        0                     0   
3                     0                   0        0                     0   
4                     0                   0        0                     0   

   yellow_crust_ooze  prognosis  
0                  0         15  
1                  0         15  
2                  0         15  
3                  0         15  
4                  0         15  

[5 rows x 133 columns]

In [ ]:
df_train['prognosis'].max()

40

In [ ]:
df_test['prognosis'] = le.transform(df_test['prognosis'])
df_test.head(20)

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0         1          1                     1                    0          0   
1         0          0                     0                    1          1   
2         0          0                     0                    0          0   
3         1          0                     0                    0          0   
4         1          1                     0                    0          0   
5         0          0                     0                    0          0   
6         0          0                     0                    0          0   
7         0          0                     0                    0          0   
8         0          0                     0                    0          0   
9         0          0                     0                    0          0   
10        0          0                     0                    0          0   
11        0          0                     0                    0          0   
12        0          0                     0                    0          0   
13        0          0                     0                    0          0   
14        1          0                     0                    0          0   
15        0          0                     0                    0          0   
16        1          1                     0                    0          0   
17        0          1                     0                    0          0   
18        0          0                     0                    0          0   
19        0          0                     0                    0          0   

    chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0        0           0             0        0                 0  ...   
1        1           0             0        0                 0  ...   
2        0           0             1        1                 1  ...   
3        0           0             0        0                 0  ...   
4        0           0             1        0                 0  ...   
5        0           0             0        0                 0  ...   
6        0           0             0        0                 0  ...   
7        0           0             0        0                 0  ...   
8        0           0             0        0                 0  ...   
9        0           0             0        0                 0  ...   
10       0           0             0        0                 0  ...   
11       0           0             0        1                 0  ...   
12       0           0             0        0                 0  ...   
13       0           0             0        0                 0  ...   
14       0           0             0        0                 0  ...   
15       1           0             0        0                 0  ...   
16       0           0             0        0                 0  ...   
17       1           1             0        0                 0  ...   
18       1           0             0        0                 0  ...   
19       0           1             0        0                 0  ...   

    blackheads  scurring  skin_peeling  silver_like_dusting  \
0            0         0             0                    0   
1            0         0             0                    0   
2            0         0             0                    0   
3            0         0             0                    0   
4            0         0             0                    0   
5            0         0             0                    0   
6            0         0             0                    0   
7            0         0             0                    0   
8            0         0             0                    0   
9            0         0             0                    0   
10           0         0             0                    0   
11           0         0             0                

In [ ]:
le.classes_

array(['(vertigo) Paroymsal  Positional Vertigo', 'AIDS', 'Acne',
       'Alcoholic hepatitis', 'Allergy', 'Arthritis', 'Bronchial Asthma',
       'Cervical spondylosis', 'Chicken pox', 'Chronic cholestasis',
       'Common Cold', 'Dengue', 'Diabetes ',
       'Dimorphic hemmorhoids(piles)', 'Drug Reaction',
       'Fungal infection', 'GERD', 'Gastroenteritis', 'Heart attack',
       'Hepatitis B', 'Hepatitis C', 'Hepatitis D', 'Hepatitis E',
       'Hypertension ', 'Hyperthyroidism', 'Hypoglycemia',
       'Hypothyroidism', 'Impetigo', 'Jaundice', 'Malaria', 'Migraine',
       'Osteoarthristis', 'Paralysis (brain hemorrhage)',
       'Peptic ulcer diseae', 'Pneumonia', 'Psoriasis', 'Tuberculosis',
       'Typhoid', 'Urinary tract infection', 'Varicose veins',
       'hepatitis A'], dtype=object)

In [ ]:
x_train = df_train.drop(columns='prognosis')
y_train = df_train['prognosis']

In [ ]:
x_train.head(2)

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          1                     1                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       0           0             0        0                 0  ...   

   pus_filled_pimples  blackheads  scurring  skin_peeling  \
0                   0           0         0             0   
1                   0           0         0             0   

   silver_like_dusting  small_dents_in_nails  inflammatory_nails  blister  \
0                    0                     0                   0        0   
1                    0                     0                   0        0   

   red_sore_around_nose  yellow_crust_ooze  
0                     0                  0  
1                     0                  0  

[2 rows x 132 columns]

In [ ]:
y_train.head(2)

0    15
1    15
Name: prognosis, dtype: int64

In [ ]:
x_test = df_test.drop(columns='prognosis')
y_test = df_test['prognosis']

In [ ]:
print(y_train[:1])
y_train = keras.utils.to_categorical(y_train, num_classes=41)
print(y_train[:1])

0    15
Name: prognosis, dtype: int64
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
print(y_train[:2])

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
from keras.models import Sequential
from keras.layers import Dense, Dropout

In [ ]:
x_train.shape

(4920, 132)

In [ ]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(x_train.shape[-1],)))
model.add(Dense(units=32, activation='relu'))
model.add(Dropout(0.25))
model.add(Dense(units=32, activation='relu'))
model.add(Dropout(0.25))
model.add(Dense(units=41, activation='softmax'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
model.compile(optimizer='Adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 32)                  │           4,256 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 32)                  │           1,056 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ (None, 32)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 32)                  │           1,056 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_1 (Dropout)                  │ (None, 32)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 41)                  │           1,353 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 7,721 (30.16 KB)

 Trainable params: 7,721 (30.16 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.fit(x_train, y_train, batch_size=1000, epochs=50, verbose=2)

Epoch 1/50
5/5 - 2s - 459ms/step - accuracy: 0.0333 - loss: 3.7176
Epoch 2/50
5/5 - 0s - 40ms/step - accuracy: 0.0551 - loss: 3.6785
Epoch 3/50
5/5 - 0s - 28ms/step - accuracy: 0.0904 - loss: 3.6396
Epoch 4/50
5/5 - 0s - 25ms/step - accuracy: 0.1215 - loss: 3.5979
Epoch 5/50
5/5 - 0s - 31ms/step - accuracy: 0.1518 - loss: 3.5553
Epoch 6/50
5/5 - 0s - 29ms/step - accuracy: 0.1825 - loss: 3.4973
Epoch 7/50
5/5 - 0s - 26ms/step - accuracy: 0.2045 - loss: 3.4299
Epoch 8/50
5/5 - 0s - 27ms/step - accuracy: 0.2091 - loss: 3.3570
Epoch 9/50
5/5 - 0s - 18ms/step - accuracy: 0.2356 - loss: 3.2550
Epoch 10/50
5/5 - 0s - 28ms/step - accuracy: 0.2396 - loss: 3.1481
Epoch 11/50
5/5 - 0s - 27ms/step - accuracy: 0.2569 - loss: 3.0312
Epoch 12/50
5/5 - 0s - 28ms/step - accuracy: 0.2701 - loss: 2.9129
Epoch 13/50
5/5 - 0s - 15ms/step - accuracy: 0.3071 - loss: 2.7534
Epoch 14/50
5/5 - 0s - 28ms/step - accuracy: 0.3315 - loss: 2.6269
Epoch 15/50
5/5 - 0s - 14ms/step - accuracy: 0.3559 - loss: 2.4865
Epo

In [ ]:
prediction = model.predict(x_test)
print(prediction[:1])

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step
[[3.16042751e-05 2.93300927e-05 8.36131107e-07 1.17507814e-04
  4.21321192e-06 6.73007776e-07 9.47137305e-05 5.27039163e-07
  1.45214770e-04 2.15947075e-05 2.02128689e-07 1.24879193e-07
  1.17247779e-04 3.07240589e-06 3.71793605e-04 9.87773657e-01
  1.53414672e-03 2.48346350e-06 2.63914699e-04 2.94731490e-05
  2.11735050e-06 3.51160594e-08 7.22757676e-08 2.15045093e-05
  9.49165440e-07 4.98862619e-07 5.16795524e-07 7.26298604e-05
  3.98811790e-06 3.31157040e-08 2.17904017e-06 3.17976868e-04
  6.03017654e-08 3.44727887e-05 7.37333403e-06 8.93294811e-03
  8.79665606e-07 2.81419972e-08 1.95355170e-07 5.87714749e-05
  4.54739251e-07]]


In [ ]:
prediction = np.argmax(prediction, axis=-1)
print(prediction[:5])

[15  4 16  9 14]


In [ ]:
print(y_test[:5])

0    15
1     4
2    16
3     9
4    14
Name: prognosis, dtype: int64


In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [ ]:
print(accuracy_score(y_test, prediction))

0.9761904761904762


In [ ]:
print(confusion_matrix(y_test, prediction))

[[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]
